name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          cd kargo-server
          git add .
          git stash
          git checkout main
          git pull
          npm install
          tsc
          pm2 delete kargo-server
          pm2 start server.js --name kargo-server
          '
